# frozen_string_literal: true

# GENERATED FILE — do not edit. Source: contract/contract.json (core 2cc44c16f516).
# Regenerate with: rake codegen

require_relative "route"

module Oblodai
  module Contract
    # Commit of the core the contract snapshot was exported from.
    CORE_COMMIT = "2cc44c16f516d6c26d6290dcada40b7ed814d6de"
    # When the snapshot was exported (RFC 3339).
    EXPORTED_AT = "2026-08-26T15:26:29Z"
    # SHA-256 of contract/contract.json — sent in the User-Agent so support can pin the vocabulary.
    CONTRACT_HASH = "de2c4a5d15d13036fc63d301c1b28209f47189e54692fcb9523bb30e5fa39652"

    # Every merchant-facing route the core declares, keyed exactly as its conformance table keys
    # them ("METHOD /path"). Path templates keep their `{name}` segments.
    #
    # @return [Hash{String => Oblodai::Contract::Route}] frozen registry of 107 routes
    ROUTES = {
      "POST /v1/api-allowlist/add" => Route.new(method: "POST", path: "/v1/api-allowlist/add", auth: :key, idempotent: false, safe: false, bare: false, list: :plain).freeze,
      "POST /v1/api-allowlist/enable" => Route.new(method: "POST", path: "/v1/api-allowlist/enable", auth: :key, idempotent: false, safe: false, bare: false, list: :plain).freeze,
      "POST /v1/api-allowlist/list" => Route.new(method: "POST", path: "/v1/api-allowlist/list", auth: :key, idempotent: false, safe: true, bare: false, list: :plain).freeze,
      "POST /v1/api-allowlist/remove" => Route.new(method: "POST", path: "/v1/api-allowlist/remove", auth: :key, idempotent: false, safe: false, bare: false, list: :plain).freeze,
      "POST /v1/auto-withdraw/delete" => Route.new(method: "POST", path: "/v1/auto-withdraw/delete", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/auto-withdraw/list" => Route.new(method: "POST", path: "/v1/auto-withdraw/list", auth: :key, idempotent: false, safe: true, bare: false, list: :plain).freeze,
      "POST /v1/auto-withdraw/set" => Route.new(method: "POST", path: "/v1/auto-withdraw/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/balance" => Route.new(method: "POST", path: "/v1/balance", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/batch/info" => Route.new(method: "POST", path: "/v1/batch/info", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "GET /v1/claim/{token}" => Route.new(method: "GET", path: "/v1/claim/{token}", auth: :public, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/claim/{token}" => Route.new(method: "POST", path: "/v1/claim/{token}", auth: :public, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "GET /v1/currencies" => Route.new(method: "GET", path: "/v1/currencies", auth: :public, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "GET /v1/documents/balance" => Route.new(method: "GET", path: "/v1/documents/balance", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "GET /v1/documents/batch" => Route.new(method: "GET", path: "/v1/documents/batch", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "GET /v1/documents/fees" => Route.new(method: "GET", path: "/v1/documents/fees", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "POST /v1/documents/jobs" => Route.new(method: "POST", path: "/v1/documents/jobs", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "GET /v1/documents/jobs/file" => Route.new(method: "GET", path: "/v1/documents/jobs/file", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "POST /v1/documents/jobs/info" => Route.new(method: "POST", path: "/v1/documents/jobs/info", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "GET /v1/documents/ledger" => Route.new(method: "GET", path: "/v1/documents/ledger", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "GET /v1/documents/link" => Route.new(method: "GET", path: "/v1/documents/link", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "GET /v1/documents/referrals" => Route.new(method: "GET", path: "/v1/documents/referrals", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "GET /v1/documents/split" => Route.new(method: "GET", path: "/v1/documents/split", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "GET /v1/documents/statement" => Route.new(method: "GET", path: "/v1/documents/statement", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "GET /v1/documents/wallet/statement" => Route.new(method: "GET", path: "/v1/documents/wallet/statement", auth: :key, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "GET /v1/documents/{kind}/{id}" => Route.new(method: "GET", path: "/v1/documents/{kind}/{id}", auth: :public, idempotent: false, safe: true, bare: true, list: nil).freeze,
      "POST /v1/exchange-rate/list" => Route.new(method: "POST", path: "/v1/exchange-rate/list", auth: :public, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "GET /v1/link/{id}" => Route.new(method: "GET", path: "/v1/link/{id}", auth: :public, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/link/{id}/checkout" => Route.new(method: "POST", path: "/v1/link/{id}/checkout", auth: :public, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/merchants" => Route.new(method: "POST", path: "/v1/merchants", auth: :onboard, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/merchants/{id}/sandbox" => Route.new(method: "POST", path: "/v1/merchants/{id}/sandbox", auth: :onboard, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "GET /v1/pay/{id}" => Route.new(method: "GET", path: "/v1/pay/{id}", auth: :public, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "GET /v1/pay/{id}/qr" => Route.new(method: "GET", path: "/v1/pay/{id}/qr", auth: :public, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/pay/{id}/select" => Route.new(method: "POST", path: "/v1/pay/{id}/select", auth: :public, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment" => Route.new(method: "POST", path: "/v1/payment", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/accepted/list" => Route.new(method: "POST", path: "/v1/payment/accepted/list", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/payment/accepted/set" => Route.new(method: "POST", path: "/v1/payment/accepted/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/accuracy/get" => Route.new(method: "POST", path: "/v1/payment/accuracy/get", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payment/accuracy/set" => Route.new(method: "POST", path: "/v1/payment/accuracy/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/autorefund/get" => Route.new(method: "POST", path: "/v1/payment/autorefund/get", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payment/autorefund/set" => Route.new(method: "POST", path: "/v1/payment/autorefund/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/batch" => Route.new(method: "POST", path: "/v1/payment/batch", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/cancel" => Route.new(method: "POST", path: "/v1/payment/cancel", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/discount/list" => Route.new(method: "POST", path: "/v1/payment/discount/list", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/payment/discount/set" => Route.new(method: "POST", path: "/v1/payment/discount/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/fee-config/get" => Route.new(method: "POST", path: "/v1/payment/fee-config/get", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payment/fee-config/set" => Route.new(method: "POST", path: "/v1/payment/fee-config/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/history" => Route.new(method: "POST", path: "/v1/payment/history", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/payment/info" => Route.new(method: "POST", path: "/v1/payment/info", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payment/link" => Route.new(method: "POST", path: "/v1/payment/link", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/link/info" => Route.new(method: "POST", path: "/v1/payment/link/info", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payment/link/list" => Route.new(method: "POST", path: "/v1/payment/link/list", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/payment/link/toggle" => Route.new(method: "POST", path: "/v1/payment/link/toggle", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/qr" => Route.new(method: "POST", path: "/v1/payment/qr", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payment/refund" => Route.new(method: "POST", path: "/v1/payment/refund", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/resend" => Route.new(method: "POST", path: "/v1/payment/resend", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/resolve" => Route.new(method: "POST", path: "/v1/payment/resolve", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/send-email" => Route.new(method: "POST", path: "/v1/payment/send-email", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payment/services" => Route.new(method: "POST", path: "/v1/payment/services", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/payment/testing-webhook" => Route.new(method: "POST", path: "/v1/payment/testing-webhook", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout" => Route.new(method: "POST", path: "/v1/payout", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/approve" => Route.new(method: "POST", path: "/v1/payout/approve", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/batch" => Route.new(method: "POST", path: "/v1/payout/batch", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/calculate" => Route.new(method: "POST", path: "/v1/payout/calculate", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payout/cancel" => Route.new(method: "POST", path: "/v1/payout/cancel", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/fee-config/get" => Route.new(method: "POST", path: "/v1/payout/fee-config/get", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payout/fee-config/set" => Route.new(method: "POST", path: "/v1/payout/fee-config/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/history" => Route.new(method: "POST", path: "/v1/payout/history", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/payout/info" => Route.new(method: "POST", path: "/v1/payout/info", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payout/link" => Route.new(method: "POST", path: "/v1/payout/link", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/link/batch" => Route.new(method: "POST", path: "/v1/payout/link/batch", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/link/cancel" => Route.new(method: "POST", path: "/v1/payout/link/cancel", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/link/cheque" => Route.new(method: "POST", path: "/v1/payout/link/cheque", auth: :key, idempotent: false, safe: false, bare: true, list: nil).freeze,
      "POST /v1/payout/link/info" => Route.new(method: "POST", path: "/v1/payout/link/info", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payout/link/list" => Route.new(method: "POST", path: "/v1/payout/link/list", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/payout/mass" => Route.new(method: "POST", path: "/v1/payout/mass", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/refund-fee-config/get" => Route.new(method: "POST", path: "/v1/payout/refund-fee-config/get", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/payout/refund-fee-config/set" => Route.new(method: "POST", path: "/v1/payout/refund-fee-config/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/payout/services" => Route.new(method: "POST", path: "/v1/payout/services", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/payout/validate" => Route.new(method: "POST", path: "/v1/payout/validate", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/referral/info" => Route.new(method: "POST", path: "/v1/referral/info", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/refund/batch" => Route.new(method: "POST", path: "/v1/refund/batch", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/sandbox/deposit" => Route.new(method: "POST", path: "/v1/sandbox/deposit", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/sandbox/faucet" => Route.new(method: "POST", path: "/v1/sandbox/faucet", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/sandbox/reset" => Route.new(method: "POST", path: "/v1/sandbox/reset", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "GET /v1/sandbox/webhooks" => Route.new(method: "GET", path: "/v1/sandbox/webhooks", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/sandbox/webhooks/replay" => Route.new(method: "POST", path: "/v1/sandbox/webhooks/replay", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/split/config/get" => Route.new(method: "POST", path: "/v1/split/config/get", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/split/config/set" => Route.new(method: "POST", path: "/v1/split/config/set", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/split/recipient/optin" => Route.new(method: "POST", path: "/v1/split/recipient/optin", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/split/recipient/optin/get" => Route.new(method: "POST", path: "/v1/split/recipient/optin/get", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/split/rule" => Route.new(method: "POST", path: "/v1/split/rule", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/split/rule/delete" => Route.new(method: "POST", path: "/v1/split/rule/delete", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/split/rule/list" => Route.new(method: "POST", path: "/v1/split/rule/list", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/test-webhook/payment" => Route.new(method: "POST", path: "/v1/test-webhook/payment", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/test-webhook/payout" => Route.new(method: "POST", path: "/v1/test-webhook/payout", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/test-webhook/wallet" => Route.new(method: "POST", path: "/v1/test-webhook/wallet", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/transfer/batch" => Route.new(method: "POST", path: "/v1/transfer/batch", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/transfer/to-personal" => Route.new(method: "POST", path: "/v1/transfer/to-personal", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/transfer/to-user" => Route.new(method: "POST", path: "/v1/transfer/to-user", auth: :key, idempotent: true, safe: false, bare: false, list: nil).freeze,
      "POST /v1/vrcs" => Route.new(method: "POST", path: "/v1/vrcs", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/wallet" => Route.new(method: "POST", path: "/v1/wallet", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/wallet/block" => Route.new(method: "POST", path: "/v1/wallet/block", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/wallet/blocked-address-refund" => Route.new(method: "POST", path: "/v1/wallet/blocked-address-refund", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/wallet/qr" => Route.new(method: "POST", path: "/v1/wallet/qr", auth: :key, idempotent: false, safe: true, bare: false, list: nil).freeze,
      "POST /v1/webhooks" => Route.new(method: "POST", path: "/v1/webhooks", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
      "POST /v1/webhooks/deliveries" => Route.new(method: "POST", path: "/v1/webhooks/deliveries", auth: :key, idempotent: false, safe: true, bare: false, list: :paged).freeze,
      "POST /v1/webhooks/rotate-secret" => Route.new(method: "POST", path: "/v1/webhooks/rotate-secret", auth: :key, idempotent: false, safe: false, bare: false, list: nil).freeze,
    }.freeze
  end
end
